### ISSUE TITLE
Ý kiến 22 / 6

### ISSUE THREAD

**Issue by vudq** [Cocochi/gcollector#15]
- ~~mô tả hai dòng~~
- ~~hai scoll~~
- ~~từ sát với đến~~
- ~~công việc sinh tự động đc đối sử như công việc bình thương~~
- ~~bổ sung checkbox trong lặp hàng tuần~~
- ~~lặp theo google: repeat, end, summary~~
- ~~confirm nếu ko có người nhận việc~~
- ~~kích thước các ô ko bằng nhau~~
- ~~thêm địa điểm thực hiện ra ngoài~~
- ~~chỉnh giao diện địa điểm, File đính kèm~~
- ~~popup full chiều cao~~
  -~~lịch sử : chỉ trace khi thay đổi trạng thái~~
- ~~phản hồi  thành trao đổi công việc~~
- ~~mô tả trên một dòng~~

**Comment by vudq** [comment]
- ~~xuất thông tin~~
- ~~check mới hiện thị các button.~~
- ~~thêm người báo cáo~~
- ~~fix header mobile~~

**Comment by Cocochi** [comment]
1.
- ~~Ẩn nhãn công việc trong thông tin chung~~
- ~~Lịch sử công việc  đổi tên thành Thông tin hoạt động~~
- ~~Thay đổi lại giao diện thông tin hoạt động như activity~~
- ~~Đánh giá thành đánh giá công việc~~
- ~~Thông tin chung giãn độ rộng của nhãn~~

2 .Danh sách công việc 
- ~~Để mô tả xuống dòng~~
- ~~Quá hạn chưa hoàn thành và đã hoàn thành ; chuyền nền ngày và trạng thái sang màu khác~~  
- ~~Bổ sung tìm kiếm công việc người giao việc với người đăng nhập là owner~~

**Comment by Cocochi** [comment]
Mobile 
- ~~Cuộn header mobile~~
- ~~Đổi trạng thái công việc nhanh qua bấm vào trạng thái công việc~~
- ~~Đánh giá đưa vào chi tiết~~
- ~~Thay nút đánh giá ngoài cùng thành nút checkin~~
  -~~Thay icon lưu công việc~~
- ~~Biểu mẫu  => Thu thập~~
- ~~Thêm nút back khi thêm mới công việc~~
- ~~Giao diện thông tin chung khi sửa công việc sẽ như thêm mới~~
- ~~Người giao sẽ sửa được thông tin này~~
- ~~Tính năng lưu lại email người đăng nhập để khi logout điền sẵn email lần trước~~
- Tính năng check được phiên bản mobile có mới nhất không để thông báo đề nghị update

**Comment by vudq** [comment]
Nhưng cái ưu tiên sau (vì chưa có tiền lệ sử dụng hoặc khó): Tệp đính kèm bổ sung google driver, dropbox
