### ISSUE TITLE
Web - Chức năng công việc

### ISSUE THREAD

**Issue by nguyendangcuong** [Cocochi/gcollector#16]
- ~~Khi vào chức năng công việc --> thời gian không để tất cả --> Hiện tại để thành tháng này cho giống bên Tổng quan~~
- ~~Khi xem chi tiết một công việc --> In phiếu công việc --> bỏ phần "Nhập thông tin mở rộng qua kéo thả vảo đây"~~

**Comment by Cocochi** [comment]
done
