### ISSUE TITLE
Web - Kết xuất số liệu trong giao diện khai thác dữ liệu

### ISSUE THREAD

**Issue by nguyendangcuong** [Cocochi/gcollector#20]
Trong giao diện khai thác dữ liệu.
Chức năng "Kết xuất excel" --> thực hiện xuất nhưng không mở ra tab kết xuất để người dùng tải dữ liệu về --> người dùng không biết vào đâu để tải dữ liệu vừa kết xuất

Đề xuất: Chức năng này cũng phải có một số tùy chọn như chức năng xuất gốc (Định dạng, hình ảnh, ...) sau khi lựa chọn --> chấp nhận --> thực hiện xuất và mở ra tab "http://app.mobiwork.vn/exports/" để người dùng có thể tải dữ liệu về

**Comment by Cocochi** [comment]
Đã xử lý như Water
