### ISSUE TITLE
Các nội dung hoàn thiện V 1.0

### ISSUE THREAD

**Issue by vudq** [Cocochi/gcollector#24]
Mobile
- ~~Danh sách công việc trên mobile không phân biêt theo Role, tất cả đều cung câp 3 view chính: Công việc của tôi, Công việc tôi giao, công việc liên quan), Riêng Manager và Owner có thêm chức năng thêm mới công việc.~~
- ~~Trong danh sách công việc căn chỉnh lại nút notify, giới hạn nội dung chi tiết công việc trong khoảng 3 dòng (cắt bớt nếu dài quá), hiện thị ngày băt đầu(kết thúc) thay cho ngày tạo công việc.~~
- ~~Checkin khi không lấy được vị trí thì phải cảnh báo người dùng để họ có thể hủy checkin bật GPS rồi checkin lại.~~
- ~~Thêm link vào số lượng checkin để chuyển sang giao diện bản đồ checkin. Bản đồ checkin nên hiện thị lần checkin cuối với biểu tượng khác.~~
  -~~Công việc minh giao thì bên ngoài ko cho checkin nhưng bên trong chi tiết lại cho checkin~~
  -~~Giao diện comment trên máy độ phân giải thấp, bàn phím che textbox không nhìn thấy nội dung nhập, Kiểm tra lại giao diện trên các máy có độ phân giải thấp.~~
  -~~Xóa commen, có hỏi confirm nhưng đã xóa trước đấy rồi~~
  -~~Đánh gia công việc: Ko biết đc công việc đã đc đánh giá hay chưa, khi bấm vào ánh giá lai hiện thị mặc định là hai giá trị Hoàn thành/ đạt nên ko biết đây là thông tin đã đánh giá hay chưa. Cần có cách hiện thị để biết đánh giá hay chưa, trong các combo cần thêm một option có giá trị rỗng hoặc chuỗi gì đấy thông nhất với trên WEB~~
  -~~Giao diện chọn người(liên quan, báo cáo,..) ko giữ lại các người đã chọn để biết để chọn thệm hoặc bỏ đi, Kiểm tra với các tình huống tương tự với các dialog chọn khác như "Loại công việc"~~
  -~~Phần thông tin "Lặp lại" chưa rõ (cái này nếu chưa xử lý thì nên ẩn)~~
- ~~Giao diện chọn địa chỉ trên bản đồ cần hiện thị ô địa chỉ, nhận nội dung đã nhập bên giao trước nếu có. Trên bản đồ cho phép xác định vị trí bằng 3 các: di chuyển trên bản đồ, lấy theo vị trị hiện tại (GPS) -> địa chỉ, geocode theo địa chỉ nhập vào-> vị trí để có cặp thông tin đầy đủ(Address/Location)~~
- ~~Thêm mới công việc: Khó chạm vào ô mô tả(có thể do độ phân giải), sau khi chạy một thời gian không chọn đc người nhận, người liên quan, ....~~
- ~~Chụp ảnh trong thông tin mở rông của công việc, save, syns vẫn ko thấy ảnh~~

**Comment by vudq** [comment]
Tông quan (Dashboard)
- ~~Widget chọn thời gian khác với các Widget chuẩn~~
- ~~Chỉ hiện thị loại công việc nếu có công việc thuộc loại đấy~~
- ~~Thông tin thời gian không đc gửi khi chuyển từ ORG Dashboar sang Group Dashboard nên dẫn đến thông tin hiện thị không thông nhất, tương tự từ Group sang Personal~~
- ~~Đổi các ULR : orgdashboard, groupdashboard, personaldashboard~~
- ~~Không dùng email làm tham số truy cập personal dashboard(Đã chuyển sang dùng id của user làm tham số truyền qua URL)~~ 
- ~~Thông tin tổng hợp của GroupDashboard không đúng(Lấy thông tin tổng hợp của OrgDashboard)~~
- ~~Đối với Manager, Trong GroupDashboard chỉ nên hiện thị các phòng bàn mà người đấy là member(hiện tại đang hiện hết)~~

**Comment by vudq** [comment]
Công việc (WEB)
- ~~Chỉnh sửa giao diện bản đồ~~
  -~~Loại công việc hiện thị hết sẽ không hợp lý trong trường hợp có nhiều loại công việc cho các phòng ban khác nhau trong tổ chức.~~
- ~~Có hiện tượng công việc không có trạng thái(không hiện nhãn trạng thái) do trên mobile~~
- ~~Thống nhất cơ chế cho button Notify:disable nếu ko có quyền notify~~
- Trong phần thông tin mở rộng theo loại công việc, thêm đc các trường Repeat.
- ~~Phần mô tả công việc: phải hiện thị đc nhiều dòng(để người giao việc mô tả theo gạch đầu dòng~~

**Comment by nguyendangcuong** [comment]
Mobile:
~~\+ Giao diện mấy button ở toolbar header trong danh sách công việc hơi bị lệch xuống dưới ở máy tablet~~
- ~~Các chức năng tương ứng với từng vai trò người dùng khác nhau (Manager, member) trong trong danh sách công việc (thêm mới công việc), trong chi tiết công việc (notify, đánh giá, checkin,...), người nhận việc được cập nhật những thông tin?,.... rà soát lại để thống nhất.~~

**Comment by hangntt** [comment]
- Chức năng xem Chọn đối tượng bản ghi trên lưới nằm ngang và lưới dưới, những bản ghi không có vị trí không gian nhưng trên bản đồ vẫn select đối tượng có vị trí không gian được chọn trước đó
- Hiển thị danh sách công việc: nội dung công việc nhiều chưa kéo dài ra phía mấy biểu tượng bên phải.
- Giao diện xem bản ghi và thêm mới bản ghi trên web của phần thu thập chưa kéo dài hết màn hình

**Comment by thoathoa91** [comment]
Web:
- ~~ô textbox tự động mở rộng theo độ dài của kí tự nhập ở phiếu thu thập thông tin~~
- ~~Lọc theo trạng thái công việc: bổ sung lọc hoàn thành nhưng đã quá hạn~~

**Comment by thoathoa91** [comment]
Mobile:
- ~~Lọc công việc. phần lọc theo trạng thái công việc có việc hoàn thành và chưa hoàn thành. Hiện tại đang lọc  theo tất cả công việc không có ý nghĩa thực tế. Nên điều chỉnh. ví dụ: việc của tôi->chưa hoàn thành hoặc việc tôi giao -> chưa hoàn thành,.... thực tế hơn~~
- ~~Xem chi tiết công việc các ô textbox  ko tự wrap text~~

**Comment by thoathoa91** [comment]
Mobile:
~~\- Cập nhật thông tin làm việc không lưu được báo " Tên công việc không được bỏ trống" trong khi có tên công việc rồi~~

**Comment by thoathoa91** [comment]
Mobile:
- xem Vị trí thực hiện công việc nên để jong fbook, kích vào bản đồ sẽ bung ra giao diện bản đồ, người dùng có thể zoom to, zoom nhỏ. Chứ hiện tại để ảnh vị trí cũng không xem rõ đc vị trí giao là ở đâu, đường nào

**Comment by thoathoa91** [comment]
Web
 -~~Công việc: phần địa điểm thực hiện mình đã có nhiều bản đồ nền, nên tận dụng cho luôn vào để người dùng có thể luân chuẩn giữa các bản đồ nền giống như phần giám sát và thu thập (dữ liệu)~~

**Comment by vudq** [comment]
Quản lý "Loại công việc"
-~~Khi thêm thành viên chỉ hiện thị những người có role=manager, vì những người này mới có quyên giao việc.~~

**Comment by Cocochi** [comment]
Danh sách công việc 
- ~~Lỗi khi copy công việc không tác dụng~~
- ~~Lỗi với người quản lý xem công việc người nào giao không tác dụng~~
- ~~Lỗi khi phân công lại công việc~~

**Comment by Cocochi** [comment]
~~Nhóm Phòng ban trên Dashboard, thêm sửa công việc đang hiện toàn bộ các phòng ban chưa list đúng phòng ban thuộc người đăng nhập~~

**Comment by Cocochi** [comment]
Done
