### ISSUE TITLE
Mobile yêu cầu từ Thoa 

### ISSUE THREAD

**Issue by Cocochi** [Cocochi/gcollector#47]
Mobile:
- xem Vị trí thực hiện công việc nên để jong fbook, kích vào bản đồ sẽ bung ra giao diện bản đồ, người dùng có thể zoom to, zoom nhỏ. Chứ hiện tại để ảnh vị trí cũng không xem rõ đc vị trí giao là ở đâu, đường nào

**Comment by thoathoa91** [comment]
Giao việc trên di động:
- ~~Lấy địa điểm thực hiện công việc chưa có cơ chế thông báo cho người giao việc biết mình đã lấy vị trí (khi lấy vị trí thực hiện công việc rồi thì biểu tượng giọt nước nên chuyển sang màu khác chả hạn)~~
- ~~Bản đồ khi lấy vị trí thực hiện cv chết~~
- ~~Quay lại xem địa điểm thực hiện thì bản đồ chết ko zoom đc~~
- ~~Chọn người liên quan, người nhận báo cáo nên hiện thị ô để tích chọn~~

**Comment by thoathoa91** [comment]
~~Các loại bản đồ nền, lớp bản đồ được tích hợp luôn vào phần giao việc: chọn vị trí thực hiện công việc, bản đồ phần Giám sát~~
